### PR TITLE
Patch for configure.in

### PR DESCRIPTION
**Pull request by arky**
Sending you patch for configure.in, Now the patch '0001-1_configure.diff' applies cleanly.

### CODE REVIEW

**Comment by imphil** [comment]
Hi,

thanks for your pull request. Did you compile everything with this new version of mozilla-central? I'm pretty sure it does not compile like this.

I'm currently working my way towards newer versions of mozilla-central, but as each version requires new patching this takes some time (and I don't have that much of it ...).

Philipp

**Comment by arky** [comment]
Thanks Philip, Am creating each patch. It is tedious, but very important
for my rural internet kiosk project in Africa.

Perhaps we can share responsibilities of maintaining this layer. My Mozilla
coding skills are not good but I can learn.

**Comment by imphil** [comment]
Hi, 

I'm doing a lot of compile-update-fix-cycles right now to get the repositories up to the latest Mozilla version, as soon that's done I'll push it online for easier collaboration. Right now the patches are a real mess and it would be hard for anyone to contribute.

Philipp

**Comment by arky** [comment]
Awesome! Looking forward to that.

**Comment by arky** [comment]
@imphil Any updates? Did you get a chance to working on this.

**Pull request closed without merging**
